name = "va-manager-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a5190f614965188b2218d06eebc4dabf"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "va-manager-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

[[kv_namespaces]]
binding = "KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[build]
command = "npm run build"

[site]
bucket = "./public"
